#!/bin/zsh

featureBranch=$1
rebaseOnto=$2

if [ -z "$featureBranch" ] || [ -z "$rebaseOnto" ] ; then
    echo "Usage:"
    echo "gitneedsrebase featureBranch rebaseOnto"
    exit 1
fi

branchpoint=$(git merge-base $featureBranch $rebaseOnto)
tipOfRebaseOnto=$(git rev-parse $rebaseOnto)

if [ "$branchpoint"  = "$tipOfRebaseOnto" ] ; then 
	echo "no"
else 
	echo "yes"
fi