#!/bin/zsh
#Text coloring functions
function color {
    if tty -s
    then
        tput setaf $2
        echo "$1"
        tput sgr0
        return
    fi
    
    echo "$1"
}

function red {
    color "$1" 1
}

function yellow {
    color "$1" 3
}

function green {
    color "$1" 2
}

#Safe say function that checks if command exists
function safe_say {
    if command -v say &> /dev/null; then
        say "$1"
    fi
}


#Prompt to continue
function confirm {
    yellow "Press y to continue, any other key to exit"
	tput bel

    read -q "variable?"
    echo ""
    if [[ $variable != "y" && $variable != "Y" ]]
    then
        red "Exiting"
        safe_say "Done"
        exit 0
    fi
    green "Continuing"
}


#Parse arguments
NO_UPDATE=false
while [[ $# -gt 0 ]]; do
    case $1 in
        --no-update)
            NO_UPDATE=true
            shift
            ;;
        *)
            red "Unknown option: $1"
            exit 1
            ;;
    esac
done

if [[ $NO_UPDATE == false ]]; then
    green "Getting current branch..."
    currentBranch=$(git rev-parse --abbrev-ref HEAD)

    green "Current branch is $currentBranch, determining ancestor..."
    branchedFrom=$(gitparent);

    green "Branched from $branchedFrom. Switching branches..."
    git checkout $branchedFrom
    sleep 1

    green "Pulling..."
    git pull

    green "Switching back to $currentBranch..."
    git checkout $currentBranch
fi

hashOfMergeBase=$(gitmergebase)
originalCommitMessage=$(git log --format=%B -n 1 $hashOfOriginalCommit)

green "Original commit message is: \n$originalCommitMessage"
green "Soft-reset to $hashOfMergeBase?"

confirm 

git reset --soft $hashOfMergeBase