#!/bin/zsh


#Text coloring functions
function color {
    if tty -s
    then
        tput setaf $2
        echo "$1"
        tput sgr0
        return
    fi
    
    echo "$1"
}

function red {
    color "$1" 1
}

function yellow {
    color "$1" 3
}

function green {
    color "$1" 2
}

#Safe say function that checks if command exists
function safe_say {
    if command -v say &> /dev/null; then
        say "$1"
    fi
}


#Prompt to continue
function confirm {
    yellow "Press y to continue, any other key to exit"
	tput bel

    read -q "variable?"
    echo ""
    if [[ $variable != "y" && $variable != "Y" ]]
    then
        red "Exiting"
        safe_say "Done"
        exit 0
    fi
    green "Continuing"
}

#Parse arguments
NO_PUSH=false
while [[ $# -gt 0 ]]; do
    case $1 in
        -n|--no-push)
            NO_PUSH=true
            shift
            ;;
        *)
            red "Unknown option: $1"
            exit 1
            ;;
    esac
done

green "Getting merge base..."
currentBranch=$(git rev-parse --abbrev-ref HEAD)
parent=$(gitparent)
hashOfMergeBase=$(git merge-base $currentBranch $parent)
mergeBaseCommitMessage=$(git log --format=oneline -n 1 $hashOfMergeBase)


green "Merge base is $mergeBaseCommitMessage"
if [ "$NO_PUSH" = false ]; then
    green "Proceed?"
    confirm
fi



green "Getting message of first commit..."
hashOfOriginalCommit=$(git rev-list $parent..HEAD | tail -1)
originalCommitMessage=$(git log --format=%B -n 1 $hashOfOriginalCommit)

green "Original commit message is: \n$originalCommitMessage"
green "Squash to original commit using that message?"

if [ "$NO_PUSH" = false ]; then
    confirm
fi
git reset --soft $hashOfMergeBase
git add -A && git commit -m "$originalCommitMessage"

if [ "$NO_PUSH" = true ]; then
    green "Squash complete. Skipping push (--no-push flag set)"
    green "Done"
    exit 0
fi

green "Force-push to origin?"
confirm
git push -f origin

green "Done"
