#!/bin/zsh

function red {
    if tty -s; then
        tput setaf 1
        echo "$1"
        tput sgr0
    else
        echo "$1"
    fi
}

if [[ -n "$SSH_CONNECTION" ]]; then
    red "SSHed into $(hostname)"
else
    red "Local machine: $(hostname)"
fi
