#!/bin/zsh

#Text coloring functions
function color {
    if tty -s
    then
        tput setaf $2
        echo "$1"
        tput sgr0
        return
    fi
    
    echo "$1"
}

function red {
    color "$1" 1
}

function yellow {
    color "$1" 3
}

function green {
    color "$1" 2
}

currentBranch=$(git rev-parse --abbrev-ref HEAD)
parent=$(gitparent) || { red "gitparent failed: $parent"; exit 1; }

commits=$(git log $parent..$currentBranch --oneline)

if [ -z "$commits" ]; then
    red "No commits found between $parent and $currentBranch"
    exit 1
fi

git log $parent..$currentBranch --oneline | tail -1 | awk '{print $1}'