#!/bin/zsh

#Text coloring functions
function color {
    if tty -s
    then
        tput setaf $2
        echo "$1"
        tput sgr0
        return
    fi
    
    echo "$1"
}

function red {
    color "$1" 1
}

function yellow {
    color "$1" 3
}

function green {
    color "$1" 2
}

#Safe say function that checks if command exists
function safe_say {
    if command -v say &> /dev/null; then
        say "$1"
    fi
}


#Prompt to continue
function confirm {
    yellow "Press y to continue, any other key to exit"
    tput bel

    read -q "variable?"
    echo ""
    if [[ $variable != "y" && $variable != "Y" ]]
    then
        red "Exiting"
        safe_say "Done"
        exit 0
    fi
    green "Continuing"
}


#exit script immediately if any command returns a non-zero exit code (indicating an error)
set -o errexit

# Assume the branch being rebased is my work, and that my work sucks.
# This means we checkout the "ours" version, which is, confusingly, the branch NOT being rebased.
git status | grep "both modified" | cut -d':' -f2- | awk {'print $1'} | xargs git checkout --ours

# Stage all the conflicted files. This will mark them as resolved.
git status | grep "both modified" | cut -d':' -f2- | awk {'print $1'} | xargs git add

# Set the GIT_EDITOR to "true". This is a clever "hack" used to bypass or suppress the text editor when performing Git operations that usually require manual input.
# Continue the rebase!
GIT_EDITOR=true git rebase --continue

